#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using RIFF.Web.Core;
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Process/ProcessingStatus.cshtml")]
    public partial class _Views_Process_ProcessingStatus_cshtml : System.Web.Mvc.WebViewPage<RIFF.Web.Core.Models.IO.ProcessingModel>
    {
        public _Views_Process_ProcessingStatus_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Process\ProcessingStatus.cshtml"
  
    ViewBag.Title = "Processing";
    ViewBag.SuppressTitle = true;
    Layout = "~/Views/Core/_RIFFPage.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" id=\"popup_container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" style=\"float: right; overflow: auto; margin: 0; padding: 20px; position: absolut" +
"e; right: 20px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"processing_indicator\"");

WriteLiteral("></div>\r\n        <div");

WriteLiteral(" id=\"continuebutton\"");

WriteLiteral(" style=\"height: 50px; width: 250px; z-index: 9500;\"");

WriteLiteral("></div>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" style=\"float: left; overflow: auto;\"");

WriteLiteral(">\r\n\r\n");

            
            #line 16 "..\..\Views\Process\ProcessingStatus.cshtml"
        
            
            #line default
            #line hidden
            
            #line 16 "..\..\Views\Process\ProcessingStatus.cshtml"
         if (!string.IsNullOrWhiteSpace(Model.FileName))
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"form processingstatusform\"");

WriteLiteral(" style=\"width: 900px; margin-bottom: 25px;\"");

WriteLiteral(" id=\"fileform\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"dx-fieldset\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"dx-fieldset-header\"");

WriteLiteral(" style=\"\"");

WriteLiteral(">Submitted File</div>\r\n                    <div");

WriteLiteral(" class=\"dx-field\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"dx-field-label\"");

WriteLiteral(" style=\"padding-left: 10px;\"");

WriteLiteral(">File Name</div>\r\n                        <div");

WriteLiteral(" class=\"dx-field-value-static\"");

WriteLiteral(" style=\"\"");

WriteLiteral(">");

            
            #line 23 "..\..\Views\Process\ProcessingStatus.cshtml"
                                                               Write(Model.FileName);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"dx-field\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"dx-field-label\"");

WriteLiteral(" style=\"padding-left: 10px;\"");

WriteLiteral(">File Size</div>\r\n                        <div");

WriteLiteral(" class=\"dx-field-value-static\"");

WriteLiteral(" style=\"\"");

WriteLiteral(">");

            
            #line 27 "..\..\Views\Process\ProcessingStatus.cshtml"
                                                               Write(Model.FileSize.ToString("#,##0"));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"dx-field\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"dx-field-label\"");

WriteLiteral(" style=\"padding-left: 10px;\"");

WriteLiteral(">File Key</div>\r\n                        <div");

WriteLiteral(" class=\"dx-field-value-static\"");

WriteLiteral(" style=\"\"");

WriteLiteral(">");

            
            #line 31 "..\..\Views\Process\ProcessingStatus.cshtml"
                                                               Write(Model.FileKey);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    </div>\r\n                </div>\r\n            </div>\r\n");

            
            #line 35 "..\..\Views\Process\ProcessingStatus.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"form processingstatusform\"");

WriteLiteral(" style=\"width: 900px;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"dx-fieldset\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"dx-fieldset-header\"");

WriteLiteral(" style=\"\"");

WriteLiteral(">Progress</div>\r\n                <div");

WriteLiteral(" class=\"dx-field\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"dx-field-label\"");

WriteLiteral(" style=\"padding-left: 10px;\"");

WriteLiteral(">Status</div>\r\n                    <div");

WriteLiteral(" class=\"dx-field-value-static\"");

WriteLiteral(" id=\"processing_status\"");

WriteLiteral(" style=\"\"");

WriteLiteral(">Initializing...</div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"dx-field\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"dx-field-label\"");

WriteLiteral(" style=\"padding-left: 10px;\"");

WriteLiteral(">Time Elapsed</div>\r\n                    <div");

WriteLiteral(" class=\"dx-field-value-static\"");

WriteLiteral(" id=\"processing_time\"");

WriteLiteral(" style=\"\"");

WriteLiteral(">-</div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"dx-field\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"dx-field-label\"");

WriteLiteral(" style=\"padding-left: 10px;\"");

WriteLiteral(">Cycles</div>\r\n                    <div");

WriteLiteral(" class=\"dx-field-value-static\"");

WriteLiteral(" id=\"progress_chart\"");

WriteLiteral(" style=\"max-height: 150px; line-height: 12px; overflow-y: auto; padding-top: 9px;" +
"\"");

WriteLiteral("></div>\r\n                </div>\r\n                ");

WriteLiteral("\r\n                <div");

WriteLiteral(" class=\"dx-field\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"dx-field-label\"");

WriteLiteral(" style=\"padding-left: 10px;\"");

WriteLiteral("># Cycles</div>\r\n                    <div");

WriteLiteral(" class=\"dx-field-value-static\"");

WriteLiteral(" id=\"finished_cycles\"");

WriteLiteral(">0</div>\r\n                </div>\r\n                ");

WriteLiteral("\r\n                <div");

WriteLiteral(" class=\"dx-field\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"dx-field-label\"");

WriteLiteral(" style=\"padding-left: 10px;\"");

WriteLiteral(">Last Process</div>\r\n                    <div");

WriteLiteral(" class=\"dx-field-value-static\"");

WriteLiteral(" id=\"processing_process\"");

WriteLiteral(" style=\"font-weight: normal;\"");

WriteLiteral(">-</div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"dx-field\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"dx-field-label\"");

WriteLiteral(" style=\"padding-left: 10px;\"");

WriteLiteral("># Updated Keys</div>\r\n                    <div");

WriteLiteral(" class=\"dx-field-value-static\"");

WriteLiteral(" id=\"processing_keys\"");

WriteLiteral(">0</div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"dx-field\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"dx-field-label\"");

WriteLiteral(" style=\"padding-left: 10px;\"");

WriteLiteral(">Processing Key</div>\r\n                    <div");

WriteLiteral(" class=\"dx-field-value-static\"");

WriteLiteral(">");

            
            #line 79 "..\..\Views\Process\ProcessingStatus.cshtml"
                                                  Write(Model.ProcessingKey);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </div>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"form processingstatusform\"");

WriteLiteral(" style=\"width: 1210px;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"dx-fieldset\"");

WriteLiteral(" style=\"width: 1200px;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"dx-field\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"dx-field-label\"");

WriteLiteral(" style=\"padding-left: 10px; width: 200px;\"");

WriteLiteral(">\r\n                        Messages\r\n                    </div>\r\n                " +
"    <div");

WriteLiteral(" class=\"dx-field-value-static\"");

WriteLiteral(" id=\"processing_messages\"");

WriteAttribute("style", Tuple.Create(" style=\"", 4939), Tuple.Create("\"", 5054)
, Tuple.Create(Tuple.Create("", 4947), Tuple.Create("width:", 4947), true)
, Tuple.Create(Tuple.Create(" ", 4953), Tuple.Create("975px;", 4954), true)
, Tuple.Create(Tuple.Create(" ", 4960), Tuple.Create("height:", 4961), true)
            
            #line 89 "..\..\Views\Process\ProcessingStatus.cshtml"
                             , Tuple.Create(Tuple.Create(" ", 4968), Tuple.Create<System.Object, System.Int32>(!string.IsNullOrWhiteSpace(Model.FileName) ? "285px" : "420px"
            
            #line default
            #line hidden
, 4969), false)
, Tuple.Create(Tuple.Create("", 5034), Tuple.Create(";", 5034), true)
, Tuple.Create(Tuple.Create(" ", 5035), Tuple.Create("overflow-y:scroll;", 5036), true)
);

WriteLiteral("></div>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n" +
"</div>\r\n\r\n");

DefineSection("RIFFPageScripts", () => {

WriteLiteral("\r\n    ");

WriteLiteral("\r\n    ");

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">

        var RFinitialize = function () {
            $('#popup_container').dxPopup({
                showTitle: true,
                title: 'Processing...',
                width: 1250,
                height: 700,
                visible: true,
                showCloseButton: false
            });

            $('#processing_indicator').dxLoadIndicator({
                height: 60,
                width: 60,
                visible: true
            });

            $('#continuebutton').dxButton({
                text: 'Continue',
                type: 'success',
                visible: false,
                onClick: function () {
");

            
            #line 122 "..\..\Views\Process\ProcessingStatus.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 122 "..\..\Views\Process\ProcessingStatus.cshtml"
                     if(!string.IsNullOrWhiteSpace(Model.ReturnUrl))
                    {

            
            #line default
            #line hidden
WriteLiteral("                        ");

WriteLiteral(" window.location.assign(\"");

            
            #line 124 "..\..\Views\Process\ProcessingStatus.cshtml"
                                              Write(Html.Raw(Model.ReturnUrl));

            
            #line default
            #line hidden
WriteLiteral("\");\r\n");

            
            #line 125 "..\..\Views\Process\ProcessingStatus.cshtml"
                                                                                                                                                                                                                                                                                                                                                    }
                    else if(!string.IsNullOrWhiteSpace(Model.ReturnAction))
                    {

            
            #line default
            #line hidden
WriteLiteral("                        ");

WriteLiteral(" window.location.assign(\"");

            
            #line 128 "..\..\Views\Process\ProcessingStatus.cshtml"
                                              Write(Html.Raw(Url.Action(Model.ReturnAction, Model.ReturnController, Model.ReturnValues)));

            
            #line default
            #line hidden
WriteLiteral("\");\r\n");

            
            #line 129 "..\..\Views\Process\ProcessingStatus.cshtml"
                                                                                                                                                                                                                                                                                                                                                    }
                    else
                    {

            
            #line default
            #line hidden
WriteLiteral("                        ");

WriteLiteral(" window.location.assign(\"");

            
            #line 132 "..\..\Views\Process\ProcessingStatus.cshtml"
                                              Write(Html.Raw(Url.Action("Index", "Home")));

            
            #line default
            #line hidden
WriteLiteral("\");\r\n");

            
            #line 133 "..\..\Views\Process\ProcessingStatus.cshtml"
                                                                                                                                                                                                                                                                                        }

            
            #line default
            #line hidden
WriteLiteral("                }\r\n            });\r\n\r\n            setTimeout(refreshStatus, 500);" +
"\r\n        };\r\n\r\n        var refreshStatus = function () {\r\n");

            
            #line 141 "..\..\Views\Process\ProcessingStatus.cshtml"
            
            
            #line default
            #line hidden
            
            #line 141 "..\..\Views\Process\ProcessingStatus.cshtml"
             if(Model.ProcessingKey == "test2")
            {

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral(" return;\r\n");

            
            #line 144 "..\..\Views\Process\ProcessingStatus.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("            $.getJSON(\"");

            
            #line 145 "..\..\Views\Process\ProcessingStatus.cshtml"
                  Write(Url.Action("RefreshProcessingStatus", "Process", new { processKey = Model.ProcessingKey }));

            
            #line default
            #line hidden
WriteLiteral("\", function (response) {\r\n                if (response.ErrorMessage) {\r\n         " +
"           DevExpress.ui.notify(\"Error: \" + response.ErrorMessage, \"error\", 5000" +
");\r\n                    $(\'#processing_status\').text(\"ERROR\")\r\n                 " +
"   $(\'#processing_status\').css(\"font-weight\", \"bold\");\r\n                    $(\'#" +
"processing_status\').css(\"color\", \"#E10000\");\r\n                    $(\"#processing" +
"_indicator\").dxLoadIndicator(\"instance\").option(\"visible\", false);\r\n            " +
"        $(\'#continuebutton\').dxButton(\'instance\').option(\'visible\', true);\r\n    " +
"                RIFFWebCore.RIFFPage.refreshSystemStatus();\r\n                } e" +
"lse {\r\n                    if (response.IsValid) {\r\n                        $(\'#" +
"processing_process\').text(response.CurrentProcess);\r\n                        $(\'" +
"#finished_cycles\').text(response.FinishedCycles);\r\n                        $(\'#p" +
"rogress_chart\').html(\'\');\r\n                        var f;\r\n                     " +
"   for(f = 0; f < response.FinishedCycles; f++) {\r\n                            $" +
"(\'<div style=\"display: inline-block; margin-right: 2px; width: 10px; height: 10p" +
"x; background-color: #768a9c;\">&nbsp;</div>\').appendTo($(\'#progress_chart\'));\r\n " +
"                       }\r\n                        for (p = 0; p < response.Proce" +
"ssingCycles; p++) {\r\n                            $(\'<div style=\"display: inline-" +
"block; margin-right: 2px; width: 10px; height: 10px; background-color: #becdda;\"" +
">&nbsp;</div>\').appendTo($(\'#progress_chart\'));\r\n                        }\r\n    " +
"                    for (r = 0; r < response.RemainingCycles; r++) {\r\n          " +
"                  $(\'<div style=\"display: inline-block; margin-right: 2px; width" +
": 10px; height: 10px; background-color: #e1ecf5;\">&nbsp;</div>\').appendTo($(\'#pr" +
"ogress_chart\'));\r\n                        }\r\n                        $(\'#process" +
"ing_time\').text(response.Time);\r\n                        $(\'#processing_keys\').t" +
"ext(response.Keys);\r\n                        if (response.Messages !== null) {\r\n" +
"                            $(\'#processing_messages\').html(response.Messages.joi" +
"n(\"<br />\"));\r\n                        }\r\n                        var mh = 420 +" +
" 16 - $(\'#progress_chart\').height();\r\n                        if ($(\'#fileform\')" +
".is(\":visible\"))\r\n                        {\r\n                            mh = mh" +
" - $(\'#fileform\').height() - 15;\r\n                        }\r\n                   " +
"     $(\'#processing_messages\').css(\'height\', mh + \'px\');\r\n                      " +
"  if (response.IsComplete) {\r\n                            $(\'#processing_status\'" +
").text(\"COMPLETE\")\r\n                            $(\'#processing_status\').css(\"fon" +
"t-weight\", \"bold\");\r\n                            $(\'#processing_status\').css(\"co" +
"lor\", \"#118FC3\");\r\n                            $(\"#processing_indicator\").dxLoad" +
"Indicator(\"instance\").option(\"visible\", false);\r\n\r\n                            i" +
"f (response.IsError) {\r\n                                $(\'#processing_status\')." +
"text(\"ERROR\")\r\n                                $(\'#processing_status\').css(\"font" +
"-weight\", \"bold\");\r\n                                $(\'#processing_status\').css(" +
"\"color\", \"#E10000\");\r\n                                $(\'#continuebutton\').dxBut" +
"ton(\'instance\').option(\'type\', \'danger\');\r\n                                $(\'#c" +
"ontinuebutton\').dxButton(\'instance\').option(\'visible\', true);\r\n                 " +
"               DevExpress.ui.notify(\"Processing complete.\", \"error\", 2000);\r\n   " +
"                             RIFFWebCore.RIFFPage.refreshSystemStatus();\r\n      " +
"                      }\r\n                            else\r\n                     " +
"       {\r\n                                $(\'#continuebutton\').dxButton(\'instanc" +
"e\').option(\'visible\', true);\r\n                                DevExpress.ui.noti" +
"fy(\"Processing complete.\", \"success\", 2000);\r\n                                RI" +
"FFWebCore.RIFFPage.refreshSystemStatus();\r\n                            }\r\n      " +
"                  } else {\r\n                            $(\'#processing_status\')." +
"text(\"In progress...\")\r\n                            setTimeout(refreshStatus, 50" +
"0);\r\n                        }\r\n                    }\r\n                    else " +
"{\r\n                        console.log(response.Error);\r\n                       " +
" setTimeout(refreshStatus, 500);\r\n                    }\r\n                }\r\n    " +
"        });\r\n        };\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
