#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using RIFF.Web.Core;
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Mapper/GraphMap.cshtml")]
    public partial class _Views_Mapper_GraphMap_cshtml : System.Web.Mvc.WebViewPage<RIFF.Web.Core.Models.Mapper.GraphMapModel>
    {
        public _Views_Mapper_GraphMap_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Mapper\GraphMap.cshtml"
  
    Layout = "~/Views/Core/_RIFFPage.cshtml";
    ViewBag.Title = "Graph Browser";
    ViewBag.SuppressTitle = true;

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\r\n\r\n<div");

WriteLiteral(" id=\"graphlist\"");

WriteLiteral("></div>\r\n<div");

WriteLiteral(" id=\"cy\"");

WriteLiteral(" style=\"width: 100%; height: 100px; margin-top: 0px;\"");

WriteLiteral("></div>\r\n\r\n");

DefineSection("RIFFPageScripts", () => {

WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 757), Tuple.Create("\"", 805)
            
            #line 17 "..\..\Views\Mapper\GraphMap.cshtml"
, Tuple.Create(Tuple.Create("", 763), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/cytoscape.min.js")
            
            #line default
            #line hidden
, 763), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 829), Tuple.Create("\"", 886)
            
            #line 18 "..\..\Views\Mapper\GraphMap.cshtml"
, Tuple.Create(Tuple.Create("", 835), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/cytoscape-cose-bilkent.js")
            
            #line default
            #line hidden
, 835), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 910), Tuple.Create("\"", 960)
            
            #line 19 "..\..\Views\Mapper\GraphMap.cshtml"
, Tuple.Create(Tuple.Create("", 916), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/jquery.qtip.min.js")
            
            #line default
            #line hidden
, 916), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 984), Tuple.Create("\"", 1033)
            
            #line 20 "..\..\Views\Mapper\GraphMap.cshtml"
, Tuple.Create(Tuple.Create("", 990), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Scripts/cytoscape-qtip.js")
            
            #line default
            #line hidden
, 990), false)
);

WriteLiteral("></script>\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1055), Tuple.Create("\"", 1107)
            
            #line 21 "..\..\Views\Mapper\GraphMap.cshtml"
, Tuple.Create(Tuple.Create("", 1062), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/jquery.qtip.min.css")
            
            #line default
            #line hidden
, 1062), false)
);

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        var cy;\r\n\r\n        var graphs = {\r\n");

            
            #line 27 "..\..\Views\Mapper\GraphMap.cshtml"
            
            
            #line default
            #line hidden
            
            #line 27 "..\..\Views\Mapper\GraphMap.cshtml"
             foreach(var g in Model.Graphs)
            {

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("\"");

            
            #line 29 "..\..\Views\Mapper\GraphMap.cshtml"
                  Write(g.Key);

            
            #line default
            #line hidden
WriteLiteral("\" : [ ");

            
            #line 29 "..\..\Views\Mapper\GraphMap.cshtml"
                              Write(Html.Raw(g.Value));

            
            #line default
            #line hidden
WriteLiteral(" ],");

WriteLiteral("\r\n");

            
            #line 30 "..\..\Views\Mapper\GraphMap.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        };\r\n\r\n        var graphName;\r\n\r\n        $(\'#graphlist\').dxSelectBox({\r\n  " +
"          width: \"300px\",\r\n            dataSource: [ ");

            
            #line 37 "..\..\Views\Mapper\GraphMap.cshtml"
                     Write(Html.Raw(string.Join(",", Model.GraphsList.Select(k => String.Format("'{0}'", k)))));

            
            #line default
            #line hidden
WriteLiteral("],\r\n            value: null,\r\n            onValueChanged: function (data) {\r\n    " +
"            graphName = data.value;\r\n                if(graphName)\r\n            " +
"    {\r\n                    showGraphMap();\r\n                }\r\n            }\r\n  " +
"      });\r\n\r\n        var showGraphMap = function () {\r\n\r\n            $(\'#cy\').he" +
"ight($(window).height() - $(\'#cy\').offset().top - 3);\r\n\r\n            RIFFWebCore" +
".RIFFPage.showLoadPanel();\r\n\r\n            cy = cytoscape({\r\n                cont" +
"ainer: $(\'#cy\'),\r\n\r\n                elements: graphs[graphName],\r\n\r\n            " +
"    style: [ // the stylesheet for the graph\r\n                  {\r\n             " +
"         selector: \'node\',\r\n                      style: {\r\n                    " +
"      \'label\': \'data(label)\',\r\n                          \'text-wrap\': \'wrap\',\r\n " +
"                         \'text-max-width\': \'50px\',\r\n                          \'w" +
"idth\': 30,\r\n                          \'height\': 30,\r\n                          \'" +
"font-size\': \'6px\',\r\n                          \'font-family\': \'Helvetica Neue, Se" +
"goe UI, Helvetica, Verdana, sans-serif\',\r\n                          \'text-halign" +
"\': \'center\',\r\n                          \'text-valign\': \'center\'\r\n               " +
"       }\r\n                  },\r\n                  {\r\n                      selec" +
"tor: \'node.transparent\',\r\n                      style: {\r\n                      " +
"    \'background-opacity\': 0.25,\r\n                          \'text-opacity\': 0.6,\r" +
"\n                      }\r\n                  },\r\n                  {\r\n           " +
"           selector: \'edge.transparent\',\r\n                      style: {\r\n      " +
"                    \'opacity\': 0.3\r\n                      }\r\n                  }" +
",\r\n                  {\r\n                      selector: \'.highlighted\',\r\n       " +
"               style: {\r\n                    //      \'font-weight\': \'bold\',\r\n   " +
"                   }\r\n                  },\r\n                  {\r\n               " +
"       selector: \'edge\',\r\n                      style: {\r\n                      " +
"    \'width\': 1,\r\n                          \'line-color\': \'#ccc\',\r\n              " +
"            \'target-arrow-color\': \'#ccc\',\r\n                      }\r\n            " +
"      },\r\n                  {\r\n                      selector: \'.edge_input\',\r\n " +
"                     style: {\r\n                          \'target-arrow-shape\': \'" +
"triangle\'\r\n                      }\r\n                  },\r\n                  {\r\n " +
"                     selector: \'.edge_output\',\r\n                      style: {\r\n" +
"                          \'target-arrow-shape\': \'triangle\'\r\n                    " +
"  }\r\n                  },\r\n                  {\r\n                      selector: " +
"\'.edge_state\',\r\n                      style: {\r\n                          \'line-" +
"style\': \'dashed\',\r\n                      }\r\n                  },\r\n              " +
"    {\r\n                      selector: \'.edge_cross\',\r\n                      sty" +
"le: {\r\n                          \'line-style\': \'dotted\',\r\n                      " +
"}\r\n                  },\r\n                  {\r\n                      selector: \'." +
"process\',\r\n                      style: {\r\n                          \'shape\': \'r" +
"oundrectangle\',\r\n                      }\r\n                  },\r\n                " +
"  {\r\n                      selector: \'.graph0\',\r\n                      style: {\r" +
"\n                          \'background-color\': \'#999999\',\r\n                     " +
" }\r\n                  },\r\n                  {\r\n                      selector: \'" +
".graph1\',\r\n                      style: {\r\n                          \'background" +
"-color\': \'#66ff66\',\r\n                      }\r\n                  },\r\n            " +
"      {\r\n                      selector: \'.graph2\',\r\n                      style" +
": {\r\n                          \'background-color\': \'#ff6666\',\r\n                 " +
"     }\r\n                  },\r\n                  {\r\n                      selecto" +
"r: \'.graph3\',\r\n                      style: {\r\n                          \'backgr" +
"ound-color\': \'#6666ff\',\r\n                      }\r\n                  },\r\n        " +
"          {\r\n                      selector: \'.graph4\',\r\n                      s" +
"tyle: {\r\n                          \'background-color\': \'#ff66ff\',\r\n             " +
"         }\r\n                  },\r\n                  {\r\n                      sel" +
"ector: \'.graph5\',\r\n                      style: {\r\n                          \'ba" +
"ckground-color\': \'#ffff66\',\r\n                      }\r\n                  },\r\n    " +
"              {\r\n                      selector: \'.graph6\',\r\n                   " +
"   style: {\r\n                          \'background-color\': \'#999999\',\r\n         " +
"             }\r\n                  },\r\n                  {\r\n                     " +
" selector: \'.graph7\',\r\n                      style: {\r\n                         " +
" \'background-color\': \'#66ff66\',\r\n                      }\r\n                  },\r\n" +
"                  {\r\n                      selector: \'.graph8\',\r\n               " +
"       style: {\r\n                          \'background-color\': \'#ff6666\',\r\n     " +
"                 }\r\n                  },\r\n                  {\r\n                 " +
"     selector: \'.graph9\',\r\n                      style: {\r\n                     " +
"     \'background-color\': \'#6666ff\',\r\n                      }\r\n                  " +
"},\r\n                  {\r\n                      selector: \'.graph10\',\r\n          " +
"            style: {\r\n                          \'background-color\': \'#ff66ff\',\r\n" +
"                      }\r\n                  },\r\n                  {\r\n            " +
"          selector: \'.graph11\',\r\n                      style: {\r\n               " +
"           \'background-color\': \'#ffff66\',\r\n                      }\r\n            " +
"      }, {\r\n                      selector: \'.key\',\r\n                      style" +
": {\r\n                          \'shape\': \'ellipse\',\r\n                          \'b" +
"ackground-color\': \'#dddddd\',\r\n                      }\r\n                  }\r\n    " +
"            ],\r\n\r\n                ready: function(event){ /* ... */ },\r\n\r\n      " +
"          // initial viewport state:\r\n                zoom: 1,\r\n                " +
"pan: { x: 0, y: 0 },\r\n\r\n                // interaction options:\r\n               " +
" minZoom: 1e-50,\r\n                maxZoom: 1e50,\r\n                zoomingEnabled" +
": true,\r\n                userZoomingEnabled: true,\r\n                panningEnabl" +
"ed: true,\r\n                userPanningEnabled: true,\r\n                boxSelecti" +
"onEnabled: false,\r\n                selectionType: \'single\',\r\n                tou" +
"chTapThreshold: 8,\r\n                desktopTapThreshold: 4,\r\n                aut" +
"olock: false,\r\n                autoungrabify: false,\r\n                autounsele" +
"ctify: false,\r\n\r\n                // rendering options:\r\n                headless" +
": false,\r\n                styleEnabled: true,\r\n                hideEdgesOnViewpo" +
"rt: false,\r\n                hideLabelsOnViewport: false,\r\n                textur" +
"eOnViewport: false,\r\n                motionBlur: false,\r\n                motionB" +
"lurOpacity: 0.2,\r\n                wheelSensitivity: 0.2,\r\n                pixelR" +
"atio: \'auto\',\r\n                initrender: function(event){ /* ... */ },\r\n      " +
"          renderer: { /* ... */ },\r\n\r\n                layout: {\r\n               " +
"     name: \'cose-bilkent\',\r\n                    ready: function () {\r\n          " +
"              // add cross-graph edges (no subject to layout)\r\n                 " +
"       if (graphName == \"ALL\") {\r\n                            cy.add([ ");

            
            #line 250 "..\..\Views\Mapper\GraphMap.cshtml"
                                Write(Html.Raw(Model.MapCytoscapeCrossGraph));

            
            #line default
            #line hidden
WriteLiteral("]);\r\n                        }\r\n                        RIFFWebCore.RIFFPage.hide" +
"LoadPanel();\r\n                  },\r\n                  idealEdgeLength: 150,\r\n   " +
"               animate: false\r\n                },\r\n                /*\r\n         " +
"       layout: {\r\n                    name: \'cose\',\r\n                    // Call" +
"ed on `layoutready`\r\n                    ready: function () { },\r\n              " +
"      // Called on `layoutstop`\r\n                    stop: function () { },\r\n   " +
"                 // Whether to animate while running the layout\r\n               " +
"     animate: true,\r\n                    // The layout animates only after this " +
"many milliseconds\r\n                    // (prevents flashing on fast runs)\r\n    " +
"                animationThreshold: 250,\r\n                    // Number of itera" +
"tions between consecutive screen positions update\r\n                    // (0 -> " +
"only updated on the end)\r\n                    refresh: 20,\r\n                    " +
"// Whether to fit the network view after when done\r\n                    fit: tru" +
"e,\r\n                    // Padding on fit\r\n                    padding: 10,\r\n   " +
"                 // Constrain layout bounds; { x1, y1, x2, y2 } or { x1, y1, w, " +
"h }\r\n                    boundingBox: undefined,\r\n                    // Extra s" +
"pacing between components in non-compound graphs\r\n                    componentS" +
"pacing: 100,\r\n                    // Node repulsion (non overlapping) multiplier" +
"\r\n                    nodeRepulsion: function (node) { return 400000; },\r\n      " +
"              // Node repulsion (overlapping) multiplier\r\n                    no" +
"deOverlap: 10,\r\n                    // Ideal edge (non nested) length\r\n         " +
"           idealEdgeLength: function (edge) { return 10; },\r\n                   " +
" // Divisor to compute edge forces\r\n                    edgeElasticity: function" +
" (edge) { return 100; },\r\n                    // Nesting factor (multiplier) to " +
"compute ideal edge length for nested edges\r\n                    nestingFactor: 5" +
",\r\n                    // Gravity force (constant)\r\n                    gravity:" +
" 80,\r\n                    // Maximum number of iterations to perform\r\n          " +
"          numIter: 10000,\r\n                    // Initial temperature (maximum n" +
"ode displacement)\r\n                    initialTemp: 200,\r\n                    //" +
" Cooling factor (how the temperature is reduced between consecutive iterations\r\n" +
"                    coolingFactor: 0.95,\r\n                    // Lower temperatu" +
"re threshold (below this point the layout will end)\r\n                    minTemp" +
": 0.5,\r\n                    // Whether to use threading to speed up the layout\r\n" +
"                    useMultitasking: true\r\n                }*/\r\n\r\n            })" +
";\r\n\r\n            cy.on(\'select\', \'node\', function (event) {\r\n                cy." +
"$(\'node:unselected\').addClass(\'transparent\');\r\n                cy.$(\'node:unsele" +
"cted\').removeClass(\'highlighted\');\r\n                cy.$(\'edge:unselected\').addC" +
"lass(\'transparent\');\r\n\r\n                var neighb = cy.$(\'node:selected\').close" +
"dNeighborhood();\r\n                neighb.removeClass(\'transparent\');\r\n          " +
"      neighb.addClass(\'highlighted\');\r\n                cy.$(\'node:selected\').con" +
"nectedEdges().removeClass(\'transparent\');\r\n            });\r\n\r\n            cy.on(" +
"\'mouseover\', \'node\', function (event) {\r\n                var node = event.cyTarg" +
"et;\r\n                node.qtip({\r\n                    content: node.data(\'info\')" +
",\r\n                    show: {\r\n                        event: event.type,\r\n    " +
"                    ready: true\r\n                    },\r\n                    hid" +
"e: {\r\n                        event: \'mouseout unfocus\'\r\n                    }\r\n" +
"                }, event);\r\n            });\r\n        }\r\n\r\n        var RFinitiali" +
"ze = function () {\r\n            //showGraphMap();\r\n        };\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
