#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using RIFF.Web.Core;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Mirror/Index.cshtml")]
    public partial class _Views_Mirror_Index_cshtml : System.Web.Mvc.WebViewPage<RIFF.Web.Core.Models.Mirror.IndexModel>
    {
        public _Views_Mirror_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Mirror\Index.cshtml"
  
    ViewBag.Title = "Received Files";
    ViewBag.SuppressTitle = true;
    ViewBag.MaxWidth = "1600px";
    Layout = "~/Views/Core/_RIFFPage.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" style=\"width: 270px; float: left; overflow: auto;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" style=\"width: 250px; vertical-align: top; display: inline-block;\"");

WriteLiteral(">\r\n        <h3");

WriteLiteral(" style=\"margin-bottom: 10px;\"");

WriteLiteral(">Received Files</h3>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" style=\"width: 250px; vertical-align: top; display: inline-block; margin-left: 10" +
"px;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" data-bind=\"dxTreeView: sourcesGrid.options\"");

WriteLiteral("></div>\r\n    </div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" style=\"width: auto; float: none; margin-left: 290px; height: 100%; position: rel" +
"ative;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" style=\"height: 50%; position: relative;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" style=\"height: auto; min-height: 100px; position: absolute; top: 0; bottom: 0; l" +
"eft: 0; right: 0; margin: 5px;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" data-bind=\"dxDataGrid: filesGrid.options\"");

WriteLiteral(" style=\"height: 100%;\"");

WriteLiteral("></div>\r\n        </div>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" style=\"height: 50%; position: relative;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" style=\"height: auto; min-height: 100px; position: absolute; top: 0; bottom: 0; l" +
"eft: 0; right: 0; margin: 5px;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" style=\"height: 30px; width: 100%; clear: both; position: absolute; top: 10px; le" +
"ft: 0px;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" style=\"width: 500px; display: inline-block; margin-left: 0px; height: 30px;\"");

WriteLiteral(" class=\"dx-field\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"dx-field-label\"");

WriteLiteral(" style=\"width: 100px;\"");

WriteLiteral(">Preview Sheet</div>\r\n                    <div");

WriteLiteral(" data-bind=\"dxSelectBox: sectionSelect.options\"");

WriteLiteral(" style=\"display: inline-block; width: 300px;\"");

WriteLiteral("></div>\r\n                </div>\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" style=\"height: 100%; width: 100%; padding-top: 45px; box-sizing: border-box;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" data-bind=\"dxDataGrid: previewGrid.options\"");

WriteLiteral(" style=\"height: 100%;\"");

WriteLiteral("></div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n");

DefineSection("RIFFPageScripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        var codeBehind = new RIFF.Web.System.MirrorPage({\r\n            urlGetF" +
"iles: \'");

            
            #line 45 "..\..\Views\Mirror\Index.cshtml"
                     Write(Html.Raw(Url.Action("GetFiles", "Mirror")));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n            urlGetFile: \'");

            
            #line 46 "..\..\Views\Mirror\Index.cshtml"
                    Write(Html.Raw(Url.Action("GetFile", "Mirror")));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n            urlGetPreview: \'");

            
            #line 47 "..\..\Views\Mirror\Index.cshtml"
                       Write(Html.Raw(Url.Action("GetPreview", "Mirror")));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n            dataSources: ");

            
            #line 48 "..\..\Views\Mirror\Index.cshtml"
                    Write(Html.Raw(Model.Sources));

            
            #line default
            #line hidden
WriteLiteral("\r\n        });\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
