#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using RIFF.Web.Core;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Data/Index.cshtml")]
    public partial class _Views_Data_Index_cshtml : System.Web.Mvc.WebViewPage<RIFF.Web.Core.Models.Data.IndexModel>
    {
        public _Views_Data_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Data\Index.cshtml"
  
    ViewBag.Title = "Data Browser";
    ViewBag.SuppressTitle = true;
    ViewBag.MaxWidth = "1920px";
    Layout = "~/Views/Core/_RIFFPage.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" style=\"width: 100%; clear: both; overflow: auto; margin-top: -5px;\"");

WriteLiteral(" id=\"outercontainer\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" style=\"width: 100%; overflow: auto; clear: both; margin-bottom: 5px;\"");

WriteLiteral(">\r\n\r\n        <div");

WriteLiteral(" style=\"width: 370px; float: left; overflow: auto;\"");

WriteLiteral(">\r\n\r\n            <div");

WriteLiteral(" style=\"width: 340px; vertical-align: top; display: inline-block;\"");

WriteLiteral(">\r\n                <h3");

WriteLiteral(" style=\"margin-bottom: 10px;\"");

WriteLiteral(">Database Browser</h3>\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" style=\"width: 340px; vertical-align: top; display: inline-block; margin-left: 10" +
"px;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"dx-field\"");

WriteLiteral(" style=\"width: 340px; margin-bottom: 10px;\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"dx-field-label\"");

WriteLiteral(" style=\"width: 35%;\"");

WriteLiteral(">Data Source:</div>\r\n                    <div");

WriteLiteral(" class=\"dx-field-value\"");

WriteLiteral(" style=\"\"");

WriteLiteral(" id=\"sourcebox\"");

WriteLiteral("></div>\r\n                </div>\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" style=\"width: 180px; float: left; margin-left: 10px;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" id=\"aggregateContainer\"");

WriteLiteral(" style=\"width: 100%; min-height: 625px; display: inline-block; vertical-align: to" +
"p; display: none;\"");

WriteLiteral(">\r\n                    Breakdown Columns:\r\n                    <div");

WriteLiteral(" id=\"aggregatebox\"");

WriteLiteral(" style=\"margin-top: 6px;\"");

WriteLiteral("></div>\r\n                </div>\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" style=\"width: 180px; float: left;\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" id=\"includeContainer\"");

WriteLiteral(" style=\"width: 100%; min-height: 625px; display: inline-block; vertical-align: to" +
"p; display: none;\"");

WriteLiteral(">\r\n                    Data Columns:\r\n                    <div");

WriteLiteral(" id=\"includebox\"");

WriteLiteral(" style=\"margin-top: 6px;\"");

WriteLiteral("></div>\r\n                </div>\r\n            </div>\r\n\r\n        </div>\r\n\r\n        " +
"<div");

WriteLiteral(" style=\"width: auto; float: none; margin-left: 380px;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"dataContainer\"");

WriteLiteral(" style=\"min-width: 300px; height: 850px; display: block; vertical-align: top;\"");

WriteLiteral(">\r\n            </div>\r\n            <div");

WriteLiteral(" id=\"footerContainer\"");

WriteLiteral(" style=\"display: none; color: #c1c8ce; text-align: right;\"");

WriteLiteral("><span");

WriteLiteral(" id=\"statusContainer\"");

WriteLiteral("></span>&nbsp;<span");

WriteLiteral(" style=\"text-decoration: underline; cursor: pointer;\"");

WriteLiteral(" onclick=\"javascript: codeBehind.showSQL();\"");

WriteLiteral(">Show SQL</span></div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n");

DefineSection("RIFFPageScripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        var codeBehind = new RIFF.Web.System.DataBrowserPage({\r\n            ur" +
"lGetAggregateQuery: \'");

            
            #line 52 "..\..\Views\Data\Index.cshtml"
                              Write(Html.Raw(Url.Action("GetAggregate", "Data")));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n            urlGetDetailQuery: \'");

            
            #line 53 "..\..\Views\Data\Index.cshtml"
                           Write(Html.Raw(Url.Action("GetDetail", "Data")));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n            urlSourceDataQuery: \'");

            
            #line 54 "..\..\Views\Data\Index.cshtml"
                            Write(Html.Raw(Url.Action("Get", "DataQuery")));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n            dataSources: ");

            
            #line 55 "..\..\Views\Data\Index.cshtml"
                    Write(Html.Raw(Model.Sources));

            
            #line default
            #line hidden
WriteLiteral("\r\n        });\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
