#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using RIFF.Web.Core;
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Core/_Attribution.cshtml")]
    public partial class _Views_Core__Attribution_cshtml : System.Web.Mvc.WebViewPage<RIFF.Web.Core.Models.AttributionModel>
    {
        public _Views_Core__Attribution_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Core\_Attribution.cshtml"
  
    Layout = "~/Views/Core/_RIFFPage.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"box\"");

WriteLiteral(" id=\"topbox\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"box1\"");

WriteLiteral(" data-options=\"dxItem: { ratio: 0.7 }\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"textlabel\"");

WriteLiteral(" class=\"dx-field-label\"");

WriteLiteral(" style=\"width: 90%;\"");

WriteLiteral(">Effective Date</div>\r\n    </div>\r\n    <div");

WriteLiteral(" id=\"box2\"");

WriteLiteral(" data-options=\"dxItem: { ratio: 1 }\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"valuedate\"");

WriteLiteral("></div>\r\n    </div>\r\n    <div");

WriteLiteral(" id=\"box3\"");

WriteLiteral(" data-options=\"dxItem: { ratio: 0.5 }\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"applyButton\"");

WriteLiteral("></div>\r\n    </div>\r\n</div>\r\n\r\n");

            
            #line 18 "..\..\Views\Core\_Attribution.cshtml"
Write(RenderSection("Help", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" id=\"gridContainer\"");

WriteLiteral(" style=\"min-height:780px; width:100%; margin: 0 auto\"");

WriteLiteral("></div>\r\n\r\n");

            
            #line 22 "..\..\Views\Core\_Attribution.cshtml"
Write(RenderSection("ColumnDefs", true));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("RIFFPageScripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">

        var initializeGrid = function (data) {
            $(""#gridContainer"").dxDataGrid({
                hoverStateEnabled: true,
                dataSource: data,

                columns: columnDefs,
                editing: {
                    mode: 'row',
                    allowUpdating: true,
                    allowDeleting: false,
                    allowAdding: false
                },
                columnChooser: { enabled: false },
                allowColumnReordering: true,
                allowColumnResizing: true,
                onRowUpdating: function (e) {
                    RIFFWebCore.Helpers.postUserAction(""");

            
            #line 43 "..\..\Views\Core\_Attribution.cshtml"
                                                   Write(Url.Action("Update", Model.ControllerName, new { valueDate = Model.ValueDate }));

            
            #line default
            #line hidden
WriteLiteral("\", $.extend(e.oldData, e.newData), \"Mapping updated.\",\r\n                        s" +
"etRequiresApply);\r\n                },\r\n                sorting: { mode: \'single\'" +
" },\r\n                columnAutoWidth: false,\r\n                pager: { visible: " +
"false },\r\n                paging: { enabled: false },\r\n                headerFil" +
"ter: { visible: true },\r\n                rowAlternationEnabled: true,\r\n         " +
"       scrolling: {\r\n                    mode: \'virtual\',\r\n                    p" +
"reloadEnabled: true\r\n                },\r\n                remoteOperations: false" +
",\r\n                loadPanel: {\r\n                    enabled: false\r\n           " +
"     },\r\n                filterRow: { visible: true },\r\n                searchPa" +
"nel: { visible: true },\r\n                selection: { mode: \'single\' }\r\n        " +
"    });\r\n        }\r\n\r\n        var getValueDate = function () {\r\n            retu" +
"rn RIFFWebCore.Helpers.getYMD($(\'#valuedate\').dxDateBox(\'instance\').option(\"valu" +
"e\"));\r\n        }\r\n\r\n        var setRequiresApply = function ()\r\n        {\r\n     " +
"       $(\'#applyButton\').dxButton(\'instance\').option(\'type\', \'default\');\r\n      " +
"  }\r\n\r\n        var RFinitialize = function () {\r\n            $(\'#topbox\').dxBox(" +
"{\r\n                direction: \'row\',\r\n                height: \'30px\',\r\n         " +
"       width: \'300px\'\r\n            });\r\n\r\n            $(\'#valuedate\').dxDateBox(" +
"{\r\n                min: null,\r\n                max: new Date(),\r\n               " +
" displayFormat: \'yyyy-MM-dd\',\r\n                value: new Date(");

            
            #line 86 "..\..\Views\Core\_Attribution.cshtml"
                           Write(Model.ValueDate.Year);

            
            #line default
            #line hidden
WriteLiteral(", ");

            
            #line 86 "..\..\Views\Core\_Attribution.cshtml"
                                                  Write(Model.ValueDate.Month);

            
            #line default
            #line hidden
WriteLiteral(" - 1, ");

            
            #line 86 "..\..\Views\Core\_Attribution.cshtml"
                                                                              Write(Model.ValueDate.Day);

            
            #line default
            #line hidden
WriteLiteral("),\r\n                onValueChanged: function (e) {\r\n                    var value" +
"Date = getValueDate();\r\n                    window.location.assign(\"");

            
            #line 89 "..\..\Views\Core\_Attribution.cshtml"
                                       Write(Url.Action("Index", Model.ControllerName, new { area = Model.AreaName }));

            
            #line default
            #line hidden
WriteLiteral("\" + \'?valueDate=\' + valueDate);\r\n                }\r\n            });\r\n\r\n          " +
"  $(\'#applyButton\').dxButton({\r\n                text: \'Apply\',\r\n                " +
"onClick: function () {\r\n                    window.location.assign(\"");

            
            #line 96 "..\..\Views\Core\_Attribution.cshtml"
                                       Write(Url.Action("Apply", Model.ControllerName, new { area = Model.AreaName, valueDate = Model.ValueDate }));

            
            #line default
            #line hidden
WriteLiteral("\");\r\n                }\r\n            });\r\n\r\n");

            
            #line 100 "..\..\Views\Core\_Attribution.cshtml"
            
            
            #line default
            #line hidden
            
            #line 100 "..\..\Views\Core\_Attribution.cshtml"
             if(Model.RequiresApply)
            {

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral(" setRequiresApply();\r\n");

            
            #line 103 "..\..\Views\Core\_Attribution.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("\r\n            RIFFWebCore.RIFFPage.populateGrid(\"");

            
            #line 105 "..\..\Views\Core\_Attribution.cshtml"
                                          Write(Url.Action("Attributions", Model.ControllerName, new { valueDate = Model.ValueDate }));

            
            #line default
            #line hidden
WriteLiteral("\", null, initializeGrid);\r\n        };\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
