#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using RIFF.Web.Core;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Core/_Layout.cshtml")]
    public partial class _Views_Core__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {

#line 96 "..\..\Views\Core\_Layout.cshtml"
public System.Web.WebPages.HelperResult RenderMenu(RIFF.Web.Core.Helpers.RFMenuItem menuItem)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 97 "..\..\Views\Core\_Layout.cshtml"
 


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    ");

WriteLiteralTo(__razor_helper_writer, " {\r\n");

WriteLiteralTo(__razor_helper_writer, "    ");

WriteLiteralTo(__razor_helper_writer, " text: \"");


#line 99 "..\..\Views\Core\_Layout.cshtml"
WriteTo(__razor_helper_writer, Html.Raw(menuItem.Text));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\", icon: \"");


#line 99 "..\..\Views\Core\_Layout.cshtml"
                  WriteTo(__razor_helper_writer, Html.Raw(menuItem.Icon));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\", disabled: ");


#line 99 "..\..\Views\Core\_Layout.cshtml"
                                                       WriteTo(__razor_helper_writer, Html.Raw(menuItem.Disabled.ToString().ToLower()));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, ",\r\n");


#line 100 "..\..\Views\Core\_Layout.cshtml"
    if (!string.IsNullOrWhiteSpace(menuItem.Action))
    {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        ");

WriteLiteralTo(__razor_helper_writer, " url: \"");


#line 102 "..\..\Views\Core\_Layout.cshtml"
WriteTo(__razor_helper_writer, Url.Action(menuItem.Action, menuItem.Controller, new { area = menuItem.Area }));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\",\r\n");


#line 103 "..\..\Views\Core\_Layout.cshtml"
    }
    else if (!string.IsNullOrWhiteSpace(menuItem.Url))
    {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        ");

WriteLiteralTo(__razor_helper_writer, " url: \"");


#line 106 "..\..\Views\Core\_Layout.cshtml"
WriteTo(__razor_helper_writer, Html.Raw(menuItem.Url));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\",\r\n");


#line 107 "..\..\Views\Core\_Layout.cshtml"
    }
    if (menuItem.SubMenu != null)
    {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        ");

WriteLiteralTo(__razor_helper_writer, " items: [\r\n");


#line 111 "..\..\Views\Core\_Layout.cshtml"
        foreach (var subMenu in menuItem.SubMenu)
        {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "            ");

WriteLiteralTo(__razor_helper_writer, " ");


#line 113 "..\..\Views\Core\_Layout.cshtml"
WriteTo(__razor_helper_writer, RenderMenu(subMenu));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n");


#line 114 "..\..\Views\Core\_Layout.cshtml"
        }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        ");

WriteLiteralTo(__razor_helper_writer, " ]\r\n");


#line 116 "..\..\Views\Core\_Layout.cshtml"
    }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    ");

WriteLiteralTo(__razor_helper_writer, " },\r\n");


#line 118 "..\..\Views\Core\_Layout.cshtml"


#line default
#line hidden
});

#line 118 "..\..\Views\Core\_Layout.cshtml"
}
#line default
#line hidden

        public _Views_Core__Layout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html");

WriteLiteral(" style=\"overflow-y: scroll;\"");

WriteLiteral(">\r\n");

            
            #line 3 "..\..\Views\Core\_Layout.cshtml"
  
    var userName = RIFF.Core.RFUser.GetUserName(User);
    var presentationMode = RIFF.Web.Core.App_Start.RIFFStart.IsPresentationMode(userName);
    var menu = RIFF.Web.Core.App_Start.RIFFStart.GetMenu(User.Identity.Name, presentationMode);
    ViewBag.PresentationMode = presentationMode;

            
            #line default
            #line hidden
WriteLiteral("\r\n<head>\r\n    <meta");

WriteLiteral(" http-equiv=\"X-UA-Compatible\"");

WriteLiteral(" content=\"IE=edge\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(">\r\n    <title>");

            
            #line 13 "..\..\Views\Core\_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(" - ");

            
            #line 13 "..\..\Views\Core\_Layout.cshtml"
                       Write(menu.Name);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n    <link");

WriteLiteral(" rel=\"icon\"");

WriteLiteral(" type=\"image/png\"");

WriteLiteral(" sizes=\"32x32\"");

WriteAttribute("href", Tuple.Create(" href=\"", 629), Tuple.Create("\"", 678)
            
            #line 14 "..\..\Views\Core\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 636), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Images/favicon-32x32.png")
            
            #line default
            #line hidden
, 636), false)
);

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"icon\"");

WriteLiteral(" type=\"image/png\"");

WriteLiteral(" sizes=\"16x16\"");

WriteAttribute("href", Tuple.Create(" href=\"", 733), Tuple.Create("\"", 782)
            
            #line 15 "..\..\Views\Core\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 740), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Images/favicon-16x16.png")
            
            #line default
            #line hidden
, 740), false)
);

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteAttribute("href", Tuple.Create(" href=\"", 828), Tuple.Create("\"", 870)
            
            #line 16 "..\..\Views\Core\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 835), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Content/print.css")
            
            #line default
            #line hidden
, 835), false)
);

WriteLiteral(" media=\"print\"");

WriteLiteral(" />\r\n");

WriteLiteral("    ");

            
            #line 17 "..\..\Views\Core\_Layout.cshtml"
Write(Styles.Render("~/Content/core"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 18 "..\..\Views\Core\_Layout.cshtml"
Write(Styles.Render("~/Content/custom"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n\r\n<body");

WriteLiteral(" class=\"dx-theme-generic-typography\"");

WriteLiteral(" id=\"riffbody\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" style=\"overflow-x: auto; overflow-y: hidden; width: 100%; clear: both; height: 3" +
"9px; min-width: 1550px; top: 0px; left: 0px; position: absolute;\"");

WriteLiteral(" class=\"noprint\"");

WriteLiteral(" id=\"rifftopheader\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" id=\"header\"");

WriteLiteral(" style=\"float:left; cursor:pointer; padding: 5px;\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 1303), Tuple.Create("\"", 1399)
, Tuple.Create(Tuple.Create("", 1313), Tuple.Create("javascript:", 1313), true)
, Tuple.Create(Tuple.Create(" ", 1324), Tuple.Create("window.location.assign(\'", 1325), true)
            
            #line 23 "..\..\Views\Core\_Layout.cshtml"
                                        , Tuple.Create(Tuple.Create("", 1349), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Home", new { area = "" })
            
            #line default
            #line hidden
, 1349), false)
, Tuple.Create(Tuple.Create("", 1396), Tuple.Create("\');", 1396), true)
);

WriteLiteral(">\r\n            <img");

WriteAttribute("src", Tuple.Create(" src=\"", 1419), Tuple.Create("\"", 1468)
            
            #line 24 "..\..\Views\Core\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 1425), Tuple.Create<System.Object, System.Int32>(Url.Content("~/Images/riff_logo_29px.png")
            
            #line default
            #line hidden
, 1425), false)
);

WriteLiteral(" />\r\n            <span");

WriteLiteral(" style=\"margin: 0 0 0 3px; color: #4B6377; font-size: 20px; font-weight: normal; " +
"vertical-align: top;\"");

WriteLiteral(">");

            
            #line 25 "..\..\Views\Core\_Layout.cshtml"
                                                                                                                   Write(menu.Name);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        </div>\r\n        <div");

WriteLiteral(" id=\"menuwrapper\"");

WriteLiteral(" style=\"float:left; padding-top: 7px; padding-left: 40px;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"riffMenu\"");

WriteLiteral("></div>\r\n        </div>\r\n        <div");

WriteLiteral(" id=\"helpWrapper\"");

WriteLiteral(" style=\"float:left; padding-top: 7px; padding-left: 20px;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"riffHelp\"");

WriteLiteral("></div>\r\n        </div>\r\n        <div");

WriteLiteral(" id=\"userbox\"");

WriteLiteral(" style=\"float:right; color: #60809a;\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" id=\"presentationmode\"");

WriteLiteral(" class=\"dx-icon-photo icon\"");

WriteLiteral(" style=\"font-size: 17px; cursor: pointer; margin-right: 10px; color: #fafafa;\"");

WriteLiteral(" title=\"Presentation mode on/off\"");

WriteLiteral("></span>\r\n            <span");

WriteLiteral(" class=\"dx-icon-repeat icon\"");

WriteLiteral(" style=\"font-size: 17px; cursor: pointer; margin-right: 10px; color:#60809a;\"");

WriteLiteral(" title=\"Clone window\"");

WriteLiteral(" onclick=\"javascript: window.open(window.location.href, \'_blank\');\"");

WriteLiteral("></span>\r\n            <span");

WriteLiteral(" style=\"color: #34346b;\"");

WriteAttribute("title", Tuple.Create(" title=\"", 2432), Tuple.Create("\"", 2479)
            
            #line 36 "..\..\Views\Core\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2440), Tuple.Create<System.Object, System.Int32>(User?.Identity?.Name ?? String.Empty
            
            #line default
            #line hidden
, 2440), false)
);

WriteLiteral(">");

            
            #line 36 "..\..\Views\Core\_Layout.cshtml"
                                                                                     Write(userName);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        </div>\r\n        <div");

WriteLiteral(" style=\"float: right; margin-top: 8px; margin-right: 4px;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"statusindicator_err\"");

WriteLiteral(" style=\"display: none; margin-top: 4px; color: #f97d7d; cursor: pointer;\"");

WriteLiteral(" title=\"\"");

WriteAttribute("onclick", Tuple.Create("\r\n                 onclick=\"", 2711), Tuple.Create("\"", 2831)
, Tuple.Create(Tuple.Create("", 2739), Tuple.Create("javascript:", 2739), true)
, Tuple.Create(Tuple.Create(" ", 2750), Tuple.Create("window.open(\'", 2751), true)
            
            #line 40 "..\..\Views\Core\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2764), Tuple.Create<System.Object, System.Int32>(Html.Raw(Url.Action("ErrorQueue", "System", new { area = "" }))
            
            #line default
            #line hidden
, 2764), false)
, Tuple.Create(Tuple.Create("", 2828), Tuple.Create("\');", 2828), true)
);

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"dx-icon-clear icon\"");

WriteLiteral("></span>\r\n            </div>\r\n            <div");

WriteLiteral(" id=\"statusindicator_warn\"");

WriteLiteral(" style=\"display: none; margin-top: 4px; color: #f2cc63; cursor: pointer;\"");

WriteLiteral(" title=\"\"");

WriteAttribute("onclick", Tuple.Create("\r\n                 onclick=\"", 3037), Tuple.Create("\"", 3157)
, Tuple.Create(Tuple.Create("", 3065), Tuple.Create("javascript:", 3065), true)
, Tuple.Create(Tuple.Create(" ", 3076), Tuple.Create("window.open(\'", 3077), true)
            
            #line 44 "..\..\Views\Core\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 3090), Tuple.Create<System.Object, System.Int32>(Html.Raw(Url.Action("ErrorQueue", "System", new { area = "" }))
            
            #line default
            #line hidden
, 3090), false)
, Tuple.Create(Tuple.Create("", 3154), Tuple.Create("\');", 3154), true)
);

WriteLiteral(">\r\n                <span");

WriteLiteral(" class=\"dx-icon-clear icon\"");

WriteLiteral("></span>\r\n            </div>\r\n            <div");

WriteLiteral(" id=\"statusindicator_ok\"");

WriteLiteral(" style=\"display: none; margin-top: 4px; color: #56b156;\"");

WriteLiteral(" title=\"No Errors\"");

WriteLiteral("><span");

WriteLiteral(" class=\"dx-icon-check icon\"");

WriteLiteral("></span></div>\r\n        </div>\r\n        <div");

WriteLiteral(" style=\"float: right; margin-top: 8px; margin-right: 10px;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"workindicator\"");

WriteLiteral("></div>\r\n        </div>\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(" id=\"riffbodywrapper\"");

WriteLiteral(" style=\"visibility: hidden; width: 100%; height: 100%; padding-top: 45px; box-siz" +
"ing: border-box;\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 55 "..\..\Views\Core\_Layout.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n\r\n    <div");

WriteLiteral(" style=\"position: fixed; bottom: 0; right: 0; color: #cad5de; padding: 4px; heigh" +
"t: 16px;\"");

WriteLiteral(" class=\"noprint\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" href=\"https://www.rohatsu.com\"");

WriteAttribute("title", Tuple.Create(" title=\"", 3909), Tuple.Create("\"", 3976)
, Tuple.Create(Tuple.Create("", 3917), Tuple.Create("Powered", 3917), true)
, Tuple.Create(Tuple.Create(" ", 3924), Tuple.Create("by", 3925), true)
, Tuple.Create(Tuple.Create(" ", 3927), Tuple.Create("RIFF", 3928), true)
, Tuple.Create(Tuple.Create(" ", 3932), Tuple.Create("Framework", 3933), true)
            
            #line 59 "..\..\Views\Core\_Layout.cshtml"
, Tuple.Create(Tuple.Create(" ", 3942), Tuple.Create<System.Object, System.Int32>(RIFF.Core.RFCore.sShortVersion
            
            #line default
            #line hidden
, 3943), false)
);

WriteLiteral(" style=\"color: #cad5de; text-decoration: none; background-color: rgba(255,255,255" +
",0.6);\"");

WriteLiteral("><img");

WriteLiteral(" width=\"16\"");

WriteLiteral(" height=\"16\"");

WriteAttribute("title", Tuple.Create(" title=\"", 4093), Tuple.Create("\"", 4160)
, Tuple.Create(Tuple.Create("", 4101), Tuple.Create("Powered", 4101), true)
, Tuple.Create(Tuple.Create(" ", 4108), Tuple.Create("by", 4109), true)
, Tuple.Create(Tuple.Create(" ", 4111), Tuple.Create("RIFF", 4112), true)
, Tuple.Create(Tuple.Create(" ", 4116), Tuple.Create("Framework", 4117), true)
            
            #line 59 "..\..\Views\Core\_Layout.cshtml"
                                                                                                                                                                                   , Tuple.Create(Tuple.Create(" ", 4126), Tuple.Create<System.Object, System.Int32>(RIFF.Core.RFCore.sShortVersion
            
            #line default
            #line hidden
, 4127), false)
);

WriteLiteral(" alt=\"(c) rohatsu software studios\"");

WriteLiteral(@" src=""data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAAWywAAFssBpeGAYAAAABh0RVh0U29mdHdhcmUAcGFpbnQubmV0IDQuMC41ZYUyZQAAAOJJREFUOE+9kUsLgkAUhfv/fyMqCop2EYYkLUJ7SS/BrNBeZkVGKQXVdHQmmaJFLupwhHvPzMfcGRPJshzLfwOyYqska53Rane8auYuWs6J7ao6NpaudyGud0eSSAsNVISTuT5ioSCpxsJlUagbISFQabDgqcXW7083rOHEAHyKNmMZJ3t/Vg1bn+9ZTwimYkDm9RAs5CUVOXV9YNHcck6fAXqHyJlKk+ZtfYk2AHBvGlG9AXBv4iDHM6L+CijWupgTz4P6K4B3AKQEhe0N9QMAIx384L9QD80tv+PNARDDZfkBwCZv6opEblwAAAAASUVORK5CYII=""");

WriteLiteral(" /></a>\r\n    </div>\r\n\r\n");

WriteLiteral("    ");

            
            #line 62 "..\..\Views\Core\_Layout.cshtml"
Write(Scripts.Render("~/bundles/core"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 63 "..\..\Views\Core\_Layout.cshtml"
Write(Scripts.Render("~/bundles/custom"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 64 "..\..\Views\Core\_Layout.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 65 "..\..\Views\Core\_Layout.cshtml"
Write(RenderSection("PageScripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        var RFlayout;\r\n\r\n        $(function () {\r\n            RFlayout = new R" +
"IFF.Web.Core.LayoutBase({\r\n                urlSetPresentationMode: \'");

            
            #line 72 "..\..\Views\Core\_Layout.cshtml"
                                    Write(Url.Action("SetPresentationMode", "Process", new { area = "" }));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                isPresentationMode: ");

            
            #line 73 "..\..\Views\Core\_Layout.cshtml"
                                Write(presentationMode ? "true" : "false");

            
            #line default
            #line hidden
WriteLiteral(",\r\n                urlHelp: \'");

            
            #line 74 "..\..\Views\Core\_Layout.cshtml"
                      Write(ViewBag.HelpUrl);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n                urlSystemStatus: \'");

            
            #line 75 "..\..\Views\Core\_Layout.cshtml"
                             Write(Url.Action("GetSystemStatus", "Process", new { area = "" }));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n");

            
            #line 76 "..\..\Views\Core\_Layout.cshtml"
                
            
            #line default
            #line hidden
            
            #line 76 "..\..\Views\Core\_Layout.cshtml"
                 if (ViewBag.SuppressMenu == null)
                {

            
            #line default
            #line hidden
WriteLiteral("                    ");

WriteLiteral("\r\n                menuItems: [\r\n");

            
            #line 80 "..\..\Views\Core\_Layout.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 80 "..\..\Views\Core\_Layout.cshtml"
                     foreach(var menuItem in menu.Items)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            ");

WriteLiteral(" ");

            
            #line 82 "..\..\Views\Core\_Layout.cshtml"
                          Write(RenderMenu(menuItem));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 83 "..\..\Views\Core\_Layout.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                ],\r\n                ");

WriteLiteral("\r\n");

            
            #line 86 "..\..\Views\Core\_Layout.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                suppressMenu: ");

            
            #line 87 "..\..\Views\Core\_Layout.cshtml"
                          Write(ViewBag.SuppressMenu == null ? "false" : "true");

            
            #line default
            #line hidden
WriteLiteral(",\r\n            });\r\n\r\n            RFlayout.start();\r\n        });\r\n    </script>\r\n" +
"</body>\r\n</html>\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
