#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using RIFF.Web.Core;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Core/_RIFFPage.cshtml")]
    public partial class _Views_Core__RIFFPage_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Core__RIFFPage_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Core\_RIFFPage.cshtml"
  
    Layout = "~/Views/Core/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"dx-theme-generic-typography\"");

WriteAttribute("style", Tuple.Create(" style=\"", 94), Tuple.Create("\"", 232)
, Tuple.Create(Tuple.Create("", 102), Tuple.Create("max-width:", 102), true)
            
            #line 5 "..\..\Views\Core\_RIFFPage.cshtml"
, Tuple.Create(Tuple.Create(" ", 112), Tuple.Create<System.Object, System.Int32>(ViewBag.MaxWidth != null ? ViewBag.MaxWidth.ToString() : "1550px"
            
            #line default
            #line hidden
, 113), false)
, Tuple.Create(Tuple.Create("", 181), Tuple.Create(";", 181), true)
, Tuple.Create(Tuple.Create(" ", 182), Tuple.Create("margin:", 183), true)
, Tuple.Create(Tuple.Create(" ", 190), Tuple.Create("0", 191), true)
, Tuple.Create(Tuple.Create(" ", 192), Tuple.Create("auto;", 193), true)
, Tuple.Create(Tuple.Create(" ", 198), Tuple.Create("height:", 199), true)
, Tuple.Create(Tuple.Create(" ", 206), Tuple.Create("100%;", 207), true)
, Tuple.Create(Tuple.Create(" ", 212), Tuple.Create("position:", 213), true)
, Tuple.Create(Tuple.Create(" ", 222), Tuple.Create("relative;", 223), true)
);

WriteLiteral(" id=\"riffpagewrapper\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"loadPanel\"");

WriteLiteral("></div>\r\n");

            
            #line 7 "..\..\Views\Core\_RIFFPage.cshtml"
    
            
            #line default
            #line hidden
            
            #line 7 "..\..\Views\Core\_RIFFPage.cshtml"
     if (!string.IsNullOrWhiteSpace(ViewBag.Title) && ViewBag.SuppressTitle == null)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" style=\" top: 0px; left: 0px; position: absolute; height: 60px;\"");

WriteLiteral(">\r\n            <h3");

WriteLiteral(" id=\"pagetitle\"");

WriteLiteral(" style=\"margin-top: 24px;\"");

WriteLiteral(">");

            
            #line 10 "..\..\Views\Core\_RIFFPage.cshtml"
                                                    Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" style=\"padding-top: 60px; box-sizing: border-box; height: 100%; width: 100%;\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 13 "..\..\Views\Core\_RIFFPage.cshtml"
       Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n");

            
            #line 15 "..\..\Views\Core\_RIFFPage.cshtml"
    }
    else
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" style=\"box-sizing: border-box; height: 100%; width: 100%; position: relative;\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 19 "..\..\Views\Core\_RIFFPage.cshtml"
       Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n");

            
            #line 21 "..\..\Views\Core\_RIFFPage.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n");

DefineSection("PageScripts", () => {

WriteLiteral("\r\n");

            
            #line 25 "..\..\Views\Core\_RIFFPage.cshtml"
    
            
            #line default
            #line hidden
            
            #line 25 "..\..\Views\Core\_RIFFPage.cshtml"
     if (ViewBag.Script != null)
    {

            
            #line default
            #line hidden
WriteLiteral("        <script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 972), Tuple.Create("\"", 1006)
            
            #line 27 "..\..\Views\Core\_RIFFPage.cshtml"
, Tuple.Create(Tuple.Create("", 978), Tuple.Create<System.Object, System.Int32>(Url.Content(ViewBag.Script)
            
            #line default
            #line hidden
, 978), false)
);

WriteLiteral("></script>\r\n");

            
            #line 28 "..\..\Views\Core\_RIFFPage.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 29 "..\..\Views\Core\_RIFFPage.cshtml"
     if (ViewBag.Bundle != null)
    {

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral(" ");

            
            #line 31 "..\..\Views\Core\_RIFFPage.cshtml"
      Write(Scripts.Render(ViewBag.Bundle));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 32 "..\..\Views\Core\_RIFFPage.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 33 "..\..\Views\Core\_RIFFPage.cshtml"
Write(RenderSection("RIFFPageScripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
