#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIFF.Framework
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class GenericEmail : RazorEngine.Templating.TemplateBase<RIFF.Framework.RFGenericEmail>
    {
#line hidden

        public override void Execute()
        {


            
            #line 2 "..\..\Email\GenericEmail.cshtml"
  
    Layout = typeof(RIFF.Framework._EmailLayout).FullName;


            
            #line default
            #line hidden
WriteLiteral("<p style=\"font-family: Calibri; font-size: 11pt; color: #444; margin: 0; padding:" +
" 0;\">\r\n    ");


            
            #line 6 "..\..\Email\GenericEmail.cshtml"
Write(Raw(Model.Body));

            
            #line default
            #line hidden
WriteLiteral("\r\n</p>\r\n");


        }
    }
}
#pragma warning restore 1591
