#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIFF.Framework
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Email\ImageListEmail.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class ImageListEmail : RIFF.Framework.RFTemplateBase<RIFF.Framework.RFImageListEmailModel>
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("<html>\r\n<body style=\"margin: 0; padding: 0;\">\r\n");


            
            #line 5 "..\..\Email\ImageListEmail.cshtml"
     if (!string.IsNullOrWhiteSpace(Model.HeaderHTML))
    {

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral(" ");


            
            #line 7 "..\..\Email\ImageListEmail.cshtml"
      Write(Raw(Model.HeaderHTML));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 8 "..\..\Email\ImageListEmail.cshtml"
    }

            
            #line default
            #line hidden

            
            #line 9 "..\..\Email\ImageListEmail.cshtml"
     foreach (System.Drawing.Image image in Model.Images)
    {

            
            #line default
            #line hidden
WriteLiteral("        <img src=\"cid:");


            
            #line 11 "..\..\Email\ImageListEmail.cshtml"
                 Write(image.Tag.ToString());

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"");


            
            #line 11 "..\..\Email\ImageListEmail.cshtml"
                                             Write(image.Tag.ToString());

            
            #line default
            #line hidden
WriteLiteral("\" width=\"");


            
            #line 11 "..\..\Email\ImageListEmail.cshtml"
                                                                           Write(image.Width);

            
            #line default
            #line hidden
WriteLiteral("\" height=\"");


            
            #line 11 "..\..\Email\ImageListEmail.cshtml"
                                                                                                 Write(image.Height);

            
            #line default
            #line hidden
WriteLiteral("\" style=\"width: ");


            
            #line 11 "..\..\Email\ImageListEmail.cshtml"
                                                                                                                               Write(image.Width);

            
            #line default
            #line hidden
WriteLiteral("px; height: ");


            
            #line 11 "..\..\Email\ImageListEmail.cshtml"
                                                                                                                                                         Write(image.Height);

            
            #line default
            #line hidden
WriteLiteral("px\" />");



WriteLiteral("<br />\r\n");


            
            #line 12 "..\..\Email\ImageListEmail.cshtml"
    }

            
            #line default
            #line hidden

            
            #line 13 "..\..\Email\ImageListEmail.cshtml"
     if (!string.IsNullOrWhiteSpace(Model.FooterHTML))
    {

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral(" ");


            
            #line 15 "..\..\Email\ImageListEmail.cshtml"
      Write(Raw(Model.FooterHTML));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 16 "..\..\Email\ImageListEmail.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</body>\r\n</html>\r\n");


        }
    }
}
#pragma warning restore 1591
