#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIFF.Framework
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class ImageEmail : RIFF.Framework.RFTemplateBase<System.Drawing.Image>
    {
#line hidden

        public override void Execute()
        {

WriteLiteral("<html>\r\n<body style=\"margin: 0; padding: 0;\">\r\n    <img src=\"cid:Image\" alt=\"Imag" +
"e\" width=\"");


            
            #line 4 "..\..\Email\ImageEmail.cshtml"
                                       Write(Model.Width);

            
            #line default
            #line hidden
WriteLiteral("\" height=\"");


            
            #line 4 "..\..\Email\ImageEmail.cshtml"
                                                             Write(Model.Height);

            
            #line default
            #line hidden
WriteLiteral("\" style=\"width: ");


            
            #line 4 "..\..\Email\ImageEmail.cshtml"
                                                                                           Write(Model.Width);

            
            #line default
            #line hidden
WriteLiteral("px; height: ");


            
            #line 4 "..\..\Email\ImageEmail.cshtml"
                                                                                                                     Write(Model.Height);

            
            #line default
            #line hidden
WriteLiteral("px\" />\r\n</body>\r\n</html>\r\n");


        }
    }
}
#pragma warning restore 1591
