#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using RIFF.Web.Core;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/Error.cshtml")]
    public partial class _Views_Shared_Error_cshtml : System.Web.Mvc.WebViewPage<System.Web.Mvc.HandleErrorInfo>
    {
        public _Views_Shared_Error_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Shared\Error.cshtml"
  
    ViewBag.Title = "RIFF Error";
    Layout = "~/Views/Core/_Layout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width\"");

WriteLiteral(" />\r\n    <title>Error</title>\r\n</head>\r\n<body>\r\n    <div");

WriteLiteral(" class=\"dx-theme-generic-typography\"");

WriteLiteral(" style=\"width: 75%; margin: 0 auto; min-width: 400px;\"");

WriteLiteral(">\r\n        <hgroup>\r\n            <h1>Error</h1>\r\n        </hgroup>\r\n");

            
            #line 18 "..\..\Views\Shared\Error.cshtml"
        
            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\Shared\Error.cshtml"
         if (Model.Exception != null)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div>\r\n                <blockquote>\r\n                    <h4>Technica" +
"l information</h4>\r\n");

            
            #line 23 "..\..\Views\Shared\Error.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 23 "..\..\Views\Shared\Error.cshtml"
                     if (Model.Exception != null)
                {

            
            #line default
            #line hidden
WriteLiteral("                        <div>\r\n");

WriteLiteral("                            ");

            
            #line 26 "..\..\Views\Shared\Error.cshtml"
                       Write(Model.Exception.Message);

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n");

            
            #line 28 "..\..\Views\Shared\Error.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </blockquote>\r\n            </div>\r\n");

            
            #line 31 "..\..\Views\Shared\Error.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        <br />\r\n        <p>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 895), Tuple.Create("\"", 949)
            
            #line 34 "..\..\Views\Shared\Error.cshtml"
, Tuple.Create(Tuple.Create("", 902), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Home", new { area = "" })
            
            #line default
            #line hidden
, 902), false)
);

WriteLiteral(">Continue</a>\r\n        </p>\r\n    </div>\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
