#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using RIFF.Web.Core;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/System/Config.cshtml")]
    public partial class _Views_System_Config_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_System_Config_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\System\Config.cshtml"
  
    ViewBag.Title = "Configuration";
    Layout = "~/Views/Core/_RIFFPage.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" id=\"gridContainer\"");

WriteLiteral(" style=\"min-height:750px; width:100%; margin: 0 auto\"");

WriteLiteral("></div>\r\n\r\n");

DefineSection("RIFFPageScripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        var groupCellTemplate = function (groupCell, info) {\r\n            $(\'<" +
"div>\').html(info.text).css(\'font-weight\', \'bold\').appendTo(groupCell);\r\n        " +
"};\r\n\r\n        var initializeGrid = function (data) {\r\n            $(\"#gridContai" +
"ner\").dxDataGrid({\r\n                hoverStateEnabled: true,\r\n                da" +
"taSource: data,\r\n\r\n                columns: [\r\n\r\n                    { dataField" +
": \'Section\', caption: \'Section\', width: \"100px\", allowEditing: false, groupIndex" +
": 0 },\r\n                    { dataField: \'Item\', caption: \'Item\', width: \"100px\"" +
", allowEditing: false, groupIndex: 1 },\r\n                    { dataField: \'Key\'," +
" caption: \'Key\', width: \"200px\", allowEditing: false },\r\n                    { d" +
"ataField: \'Description\', caption: \'Description\', width: \"300px\", allowEditing: f" +
"alse },\r\n                    { dataField: \'Environment\', caption: \'Env\', width: " +
"\"60px\", allowEditing: false },\r\n                    { dataField: \'UpdateTime\', c" +
"aption: \'Updated\', dataType: \'date\', format: \"dd/MM/yyyy HH:mm:ss\", width: \"150p" +
"x\", visible: false, allowEditing: false },\r\n                    { dataField: \'Up" +
"dateUser\', caption: \'Updater\', width: \"150px\", visible: false, allowEditing: fal" +
"se },\r\n                    { dataField: \'Value\', caption: \'Value\', width: \"800px" +
"\", allowEditing: true },\r\n                    { dataField: \'UserConfigKeyID\', vi" +
"sible: false, allowEditing: false },\r\n                    { dataField: \'UserConf" +
"igValueID\', visible: false, allowEditing: false }\r\n                ],\r\n         " +
" /*      customizeColumns: function (columns) {\r\n                    $.each(colu" +
"mns, function (_, element) {\r\n                        element.groupCellTemplate " +
"= groupCellTemplate;\r\n                    });\r\n                },\r\n            *" +
"/    editing: {\r\n                mode: \'cell\',\r\n                    allowUpdatin" +
"g: true,\r\n                    allowDeleting: false,\r\n                    allowAd" +
"ding: false\r\n                },\r\n                columnChooser: { enabled: true " +
"},\r\n                allowColumnReordering: true,\r\n                allowColumnRes" +
"izing: true,\r\n                grouping: {\r\n                    autoExpandAll: fa" +
"lse\r\n                },\r\n                onRowUpdating: function (e) {\r\n        " +
"            e.element.addClass(\'nointeraction\');\r\n                    e.cancel =" +
" RIFFWebCore.Helpers.postUserAction(\"");

            
            #line 51 "..\..\Views\System\Config.cshtml"
                                                              Write(Url.Action("UpdateConfig", "System"));

            
            #line default
            #line hidden
WriteLiteral(@""", $.extend({}, e.oldData, e.newData), ""Configuration updated."");
                },
                onRowUpdated: function (e) {
                    e.element.removeClass('nointeraction');
                },
                sorting: { mode: 'single' },
                groupPanel: { visible: true, emptyPanelText: 'Drag a column header here to group grid records' },
                columnAutoWidth: false,
                pager: { visible: false },
                paging: { enabled: false },
                headerFilter: { visible: true },
                rowAlternationEnabled: true,
                //paging: { pageSize: 15 },
                scrolling: {
                    mode: 'virtual',
                    preloadEnabled: true
                },
                remoteOperations: false,
                loadPanel: {
                    enabled: false
                },
                filterRow: { visible: true },
                searchPanel: { visible: true },
                selection: { mode: 'single' }
            });
        }

        var RFinitialize = function() {
            RIFFWebCore.RIFFPage.populateGrid(""");

            
            #line 79 "..\..\Views\System\Config.cshtml"
                                          Write(Url.Action("GetConfigs", "System"));

            
            #line default
            #line hidden
WriteLiteral("\", null, initializeGrid);\r\n        };\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
