#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using RIFF.Web.Core;
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/System/DataEditor.cshtml")]
    public partial class _Views_System_DataEditor_cshtml : System.Web.Mvc.WebViewPage<RIFF.Web.Core.Models.System.DataEditorModel>
    {
        public _Views_System_DataEditor_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\System\DataEditor.cshtml"
  
    ViewBag.Title = "Data Editor";
    ViewBag.SuppressTitle = true;
    ViewBag.Bundle = "~/bundles/codemirror";
    ViewBag.MaxWidth = "1850px";
    Layout = "~/Views/Core/_RIFFPage.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" style=\"width: 100%; clear: both; overflow: auto;\"");

WriteLiteral(" id=\"outercontainer\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" style=\"width: 760px; vertical-align: top; display: inline-block;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"dx-field\"");

WriteLiteral(" style=\"width: 300px; margin-bottom: 7px;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"dx-field-label\"");

WriteLiteral(" style=\"width: 20%;\"");

WriteLiteral(">Latest Date</div>\r\n            <div");

WriteLiteral(" class=\"dx-field-value\"");

WriteLiteral(" style=\"width: 40%;\"");

WriteLiteral(" id=\"datebox\"");

WriteLiteral("></div>\r\n        </div>\r\n        <div");

WriteLiteral(" id=\"gridContainer\"");

WriteLiteral(" style=\"height: 650px; margin: 0; width: 100%;\"");

WriteLiteral("></div>\r\n    </div>\r\n    <div");

WriteLiteral(" id=\"editingPanel\"");

WriteLiteral(" style=\"min-height: 625px; margin: -20px 0 0 0;/* width: 49%;*/ display: inline-b" +
"lock; vertical-align: top;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" style=\"padding: 0 0 0 0; width: 100%;\"");

WriteLiteral(" class=\"dx-fieldset\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"dx-field\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"dx-field-label\"");

WriteLiteral(" style=\"width: 66%;\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" id=\"copybutton\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" id=\"savebutton\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" id=\"deletebutton\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" id=\"importbutton\"");

WriteLiteral("></div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"dx-field-value\"");

WriteLiteral(" style=\"width: 33%; margin-top: 6px;\"");

WriteLiteral(" id=\"keytypebox\"");

WriteLiteral("></div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"dx-field\"");

WriteLiteral(">\r\n                <textarea");

WriteLiteral(" id=\"keyeditorbox\"");

WriteLiteral(" style=\"width: 100%;\"");

WriteLiteral("></textarea>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" style=\"padding: 0 0 0 0; width: 100%;\"");

WriteLiteral(" class=\"dx-fieldset\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"dx-field\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"dx-field-label\"");

WriteLiteral(" style=\"width: 66%;\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" id=\"editbutton\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" id=\"updatebutton\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" id=\"viewbutton\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" id=\"xmlbutton\"");

WriteLiteral("></div>\r\n                    <div");

WriteLiteral(" id=\"excelbutton\"");

WriteLiteral("></div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"dx-field-value\"");

WriteLiteral(" style=\"width: 33%; margin-top: 6px;\"");

WriteLiteral(" id=\"contenttypebox\"");

WriteLiteral("></div>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"dx-field\"");

WriteLiteral(">\r\n                <textarea");

WriteLiteral(" id=\"contenteditorbox\"");

WriteLiteral(" style=\"width: 100%;\"");

WriteLiteral("></textarea>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" id=\"importentry\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n    <h3>Import Entry</h3>\r\n");

            
            #line 53 "..\..\Views\System\DataEditor.cshtml"
    
            
            #line default
            #line hidden
            
            #line 53 "..\..\Views\System\DataEditor.cshtml"
     using (Html.BeginForm("ImportEntry", "System", FormMethod.Post, new { id = "uploadform", enctype = "multipart/form-data" }))
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"dx-fieldset\"");

WriteLiteral(" style=\"width: 600px;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"dx-field\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"dx-field-label\"");

WriteLiteral(" style=\"width: 20%;\"");

WriteLiteral(">&nbsp;</div>\r\n                <div");

WriteLiteral(" class=\"dx-field-value\"");

WriteLiteral(" style=\"width: 80%;\"");

WriteLiteral("><div");

WriteLiteral(" id=\"uploadfile\"");

WriteLiteral("></div></div>\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" id=\"uploadbutton\"");

WriteLiteral("></div>\r\n");

            
            #line 62 "..\..\Views\System\DataEditor.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n");

DefineSection("RIFFPageScripts", () => {

WriteLiteral("\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n\r\n        var codeBehind = new RIFF.Web.System.DataEditorPage({\r\n            u" +
"rlGetDocumentForEdit: \'");

            
            #line 70 "..\..\Views\System\DataEditor.cshtml"
                               Write(Html.Raw(Url.Action("GetDocumentForEdit", "System")));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n            urlInvalidateEntry: \'");

            
            #line 71 "..\..\Views\System\DataEditor.cshtml"
                            Write(Html.Raw(Url.Action("InvalidateEntry", "System")));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n            urlDataSet: \'");

            
            #line 72 "..\..\Views\System\DataEditor.cshtml"
                    Write(Html.Raw(Url.Action("DataSet", "System")));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n            urlExportEntry: \'");

            
            #line 73 "..\..\Views\System\DataEditor.cshtml"
                        Write(Html.Raw(Url.Action("ExportEntry", "System")));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n            urlDownloadEntry: \'");

            
            #line 74 "..\..\Views\System\DataEditor.cshtml"
                          Write(Html.Raw(Url.Action("DownloadEntry", "System")));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n            urlUpdateDocument: \'");

            
            #line 75 "..\..\Views\System\DataEditor.cshtml"
                           Write(Html.Raw(Url.Action("UpdateDocument", "System")));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n            urlSaveDocument: \'");

            
            #line 76 "..\..\Views\System\DataEditor.cshtml"
                         Write(Html.Raw(Url.Action("SaveDocument", "System")));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n            urlGetLatestDocuments: \'");

            
            #line 77 "..\..\Views\System\DataEditor.cshtml"
                               Write(Html.Raw(Url.Action("GetLatestDocuments", "System")));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n            urlGetInstances: \'");

            
            #line 78 "..\..\Views\System\DataEditor.cshtml"
                         Write(Html.Raw(Url.Action("GetInstances", "System")));

            
            #line default
            #line hidden
WriteLiteral("\',\r\n            initialDate: new Date(");

            
            #line 79 "..\..\Views\System\DataEditor.cshtml"
                             Write(RIFF.Core.RFDate.Today().Year);

            
            #line default
            #line hidden
WriteLiteral(", ");

            
            #line 79 "..\..\Views\System\DataEditor.cshtml"
                                                             Write(RIFF.Core.RFDate.Today().Month);

            
            #line default
            #line hidden
WriteLiteral(" - 1, ");

            
            #line 79 "..\..\Views\System\DataEditor.cshtml"
                                                                                                  Write(RIFF.Core.RFDate.Today().Day);

            
            #line default
            #line hidden
WriteLiteral(")\r\n        });\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
