#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using RIFF.Web.Core;
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/System/InputReport.cshtml")]
    public partial class _Views_System_InputReport_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_System_InputReport_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\System\InputReport.cshtml"
  
    ViewBag.Title = "Input Report";
    Layout = "~/Views/Core/_RIFFPage.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div>\r\n    <div");

WriteLiteral(" id=\"applyButton\"");

WriteLiteral("></div>\r\n</div>\r\n\r\n");

            
            #line 10 "..\..\Views\System\InputReport.cshtml"
 using (Html.BeginForm("UpdateInputReport", "System", new { area = "" }, FormMethod.Post, new { id = "updateform", enctype = "multipart/form-data" }))
{

            
            #line default
            #line hidden
WriteLiteral("<input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"keyReference\"");

WriteAttribute("value", Tuple.Create(" value=\"", 339), Tuple.Create("\"", 368)
            
            #line 12 "..\..\Views\System\InputReport.cshtml"
, Tuple.Create(Tuple.Create("", 347), Tuple.Create<System.Object, System.Int32>(ViewBag.KeyReference
            
            #line default
            #line hidden
, 347), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("<input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"updates\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" id=\"updates\"");

WriteLiteral(" />\r\n");

            
            #line 14 "..\..\Views\System\InputReport.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" id=\"gridContainer\"");

WriteLiteral(" style=\"min-height:750px; width: 100%; margin: 0 auto\"");

WriteLiteral("></div>\r\n\r\n");

DefineSection("RIFFPageScripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        var updates = [];\r\n\r\n        var initializeGrid = function (data) {\r\n " +
"           /*$(\"#gridContainer\").dxPivotGrid({\r\n                dataSource: data" +
",\r\n            });*/\r\n\r\n            $(\"#gridContainer\").dxDataGrid({\r\n          " +
"      hoverStateEnabled: true,\r\n                dataSource: data,\r\n\r\n           " +
"     columnChooser: { enabled: true },\r\n                allowColumnReordering: t" +
"rue,\r\n                sorting: { mode: \'single\' },\r\n                groupPanel: " +
"{ visible: false },\r\n                columnAutoWidth: true,\r\n                pag" +
"er: { visible: false },\r\n                paging: { enabled: false },\r\n          " +
"      headerFilter: { visible: true },\r\n                scrolling: {\r\n          " +
"          mode: \'virtual\',\r\n                    preloadEnabled: true\r\n          " +
"      },\r\n                //paging: { pageSize: 15 },\r\n                remoteOpe" +
"rations: false,\r\n                loadPanel: {\r\n                    enabled: fals" +
"e\r\n                },\r\n                editing: {\r\n                    mode: \"ce" +
"ll\",\r\n                    allowUpdating: true\r\n                },\r\n             " +
"   onRowUpdated: function (e) {\r\n                    updates.push({ rowNum: e.ke" +
"y.RFRowNo, data: e.data });\r\n                },\r\n                filterRow: { vi" +
"sible: true },\r\n                searchPanel: { visible: true },\r\n               " +
" selection: { mode: \'single\' }\r\n            });\r\n        };\r\n\r\n        var RFini" +
"tialize = function () {\r\n\r\n            $(\'#applyButton\').dxButton({\r\n           " +
"     text: \'Apply Changes\', onClick: function () {\r\n                    $(\'#upda" +
"tes\').val(JSON.stringify(updates));\r\n                    $(\'#updateform\').submit" +
"();\r\n                }\r\n            });\r\n\r\n            RIFFWebCore.RIFFPage.popu" +
"lateGrid(\"");

            
            #line 70 "..\..\Views\System\InputReport.cshtml"
                                          Write(Url.Action("GetInputReport", "System", new { keyReference = ViewBag.KeyReference }));

            
            #line default
            #line hidden
WriteLiteral("\", null, initializeGrid);\r\n        };\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
