#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using RIFF.Web.Core;
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/System/Logs.cshtml")]
    public partial class _Views_System_Logs_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_System_Logs_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\System\Logs.cshtml"
  
    ViewBag.Title = "Processing Logs";
    Layout = "~/Views/Core/_RIFFPage.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" id=\"tabs\"");

WriteLiteral("></div>\r\n<div");

WriteLiteral(" id=\"tab1\"");

WriteLiteral(" class=\"tab-content\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"processContainer\"");

WriteLiteral(" style=\"min-height:500px; width:1500px; margin: 0 auto\"");

WriteLiteral(">\r\n    </div>\r\n</div>\r\n<div");

WriteLiteral(" id=\"tab2\"");

WriteLiteral(" class=\"tab-content\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"gridContainer\"");

WriteLiteral(" style=\"min-height:500px; width:1500px; margin: 0 auto\"");

WriteLiteral(">\r\n    </div>\r\n    ");

WriteLiteral("\r\n</div>\r\n\r\n");

DefineSection("RIFFPageScripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        var initializeGrid = function (data) {
            $(""#processContainer"").dxDataGrid({
                hoverStateEnabled: true,
                dataSource: data.ProcessLog,
                columns: [
                    { dataField: 'LogID', caption: 'Log ID', width: ""50px"", sortIndex: 0, sortOrder: 'desc' },
                    { dataField: 'Timestamp', caption: 'Time Stamp', dataType: 'date', format: ""dd/MM/yyyy HH:mm:ss"", width: ""150px"", alignment: 'center' },
                    { dataField: 'GraphName', caption: 'Graph', width: ""100px"" },
                    { dataField: 'ProcessName', caption: 'Process', width: ""300px"" },
                    { dataField: 'Instance', caption: 'Instance', width: ""80px"", alignment: 'center' },
                    { dataField: 'ValueDate', caption: 'Date', width: ""90px"", dataType: 'date', format: 'dd/MM/yyyy', alignment: 'center' },
                    { dataField: 'IOTime', caption: 'IO [ms]', width: ""85px"", format: 'fixedPoint' },
                    { dataField: 'ProcessingTime', caption: 'Work [ms]', width: ""85px"", format: 'fixedPoint' },
                    { dataField: 'NumUpdates', caption: '# Upd', width: ""75px"" },
                    { dataField: 'Success', caption: 'OK', width: ""50px"", dataType: ""boolean"" },
                    { dataField: 'Message', caption: 'Message', width: ""400px"" },
");

WriteLiteral("\r\n                ],\r\n                columnChooser: { enabled: false },\r\n       " +
"         allowColumnReordering: false,\r\n                sorting: { mode: \'single" +
"\' },\r\n                groupPanel: { visible: true, emptyPanelText: \'Drag a colum" +
"n header here to group grid records\' },\r\n                columnAutoWidth: true,\r" +
"\n                pager: { visible: true },\r\n                paging: { pageSize: " +
"22 },\r\n                headerFilter: { visible: true },\r\n                rowAlte" +
"rnationEnabled: true,\r\n                remoteOperations: false,\r\n               " +
" loadPanel: {\r\n                    enabled: false\r\n                },\r\n         " +
"       filterRow: { visible: true },\r\n                searchPanel: { visible: tr" +
"ue },\r\n                selection: { mode: \'single\' }\r\n            });\r\n\r\n       " +
"     $(\"#gridContainer\").dxDataGrid({\r\n                hoverStateEnabled: true,\r" +
"\n                dataSource: data.SystemLog,\r\n                columns: [\r\n      " +
"              { dataField: \'LogID\', caption: \'Log ID\', width: \"50px\" },\r\n       " +
"             { dataField: \'Timestamp\', caption: \'Time Stamp\', dataType: \'date\', " +
"format: \"dd/MM/yyyy HH:mm:ss\", sortIndex: 0, sortOrder: \'desc\', width: \"150px\" }" +
",\r\n                    { dataField: \'Hostname\', caption: \'Host Name\', width: \"10" +
"0px\" },\r\n                    { dataField: \'Level\', caption: \'Level\', width: \"75p" +
"x\" },\r\n                    { dataField: \'Source\', caption: \'Source\', width: \"200" +
"px\" },\r\n                    { dataField: \'Message\', caption: \'Message\', width: \"" +
"570px\" },\r\n                    { dataField: \'Thread\', caption: \'Thread\', width: " +
"\"50px\" },\r\n                    { dataField: \'Exception\', caption: \'Exception\', w" +
"idth: \"200px\" },\r\n                    { dataField: \'Content\', caption: \'Content\'" +
", width: \"100px\" },\r\n                    ");

WriteLiteral("\r\n                ],\r\n                columnChooser: { enabled: false },\r\n       " +
"         allowColumnReordering: false,\r\n                sorting: { mode: \'single" +
"\' },\r\n                groupPanel: { visible: true, emptyPanelText: \'Drag a colum" +
"n header here to group grid records\' },\r\n                columnAutoWidth: true,\r" +
"\n                pager: { visible: true },\r\n                paging: { pageSize: " +
"22 },\r\n                headerFilter: { visible: true },\r\n                rowAlte" +
"rnationEnabled: true,\r\n                remoteOperations: false,\r\n               " +
" loadPanel: {\r\n                    enabled: false\r\n                },\r\n         " +
"       filterRow: { visible: true },\r\n                searchPanel: { visible: tr" +
"ue },\r\n                selection: { mode: \'single\' }\r\n            });\r\n        }" +
"\r\n\r\n        var RFinitialize = function () {\r\n\r\n            $(\'#tabs\').dxTabs({\r" +
"\n                dataSource:\r\n                    [\r\n                        { t" +
"ext: \"Process Log\", content: \"#tab1\" },\r\n                        { text: \"System" +
" Log\", content: \"#tab2\" },\r\n                    ],\r\n                width: \"30%\"" +
",\r\n                selectedIndex: 0,\r\n                onItemClick: function (e) " +
"{\r\n                    $(\".tab-content\").hide();\r\n                    $(e.itemDa" +
"ta.content).show();\r\n                    if (e.itemData.content === \"#tab1\") {\r\n" +
"                        $(\'#processContainer\').dxDataGrid(\'instance\').repaint();" +
"\r\n                    } else if (e.itemData.content === \"#tab2\") {\r\n            " +
"            $(\'#gridContainer\').dxDataGrid(\'instance\').repaint();\r\n             " +
"       }\r\n                }\r\n            });\r\n\r\n            RIFFWebCore.RIFFPage" +
".populateGrid(\"");

            
            #line 147 "..\..\Views\System\Logs.cshtml"
                                          Write(Url.Action("GetLogs", "System"));

            
            #line default
            #line hidden
WriteLiteral("\", null, initializeGrid);\r\n        };\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
